### ISSUE TITLE
Active Inputs in Standalone limited to 36 inputs

### ISSUE THREAD

**Issue by MeestorX** [sonosaurus/sonobus#110]
How to reproduce:

Select an input device that has more than 36 channels.
Select channels 1-36 as "Active".
Select channel 37 as "Active"
You will see one of the other channels unselect itself (usually channel 1)

Also, would be great to have a "select all" function :-)

**Comment by essej** [comment]
Thanks, as you know, this limit is now fixed in develop. Will be available in 1.4.8 when released.

**Comment by MeestorX** [comment]
Yes! Fastest fix in history. Well done!!
