### ISSUE TITLE
No sound being sent 

### ISSUE THREAD

**Issue by user1969903** [sonosaurus/sonobus#128]
I have two computers on a wired LAN, let's call them computer A and computer B. I can send sound from B to A just fine but I can't seem to send sound from A to B. I am not sure where the problem is or how to diagnose it. 

Computer A just can't send sounds no matter what input device I select inside of SonoBus. However, the input device does work (I can use other recording apps or voice chat apps just fine). 

SonoBus itself seems to be able to get something out of the input device since I can see that the volume meter in the Audio options does move:
![image](https://user-images.githubusercontent.com/33215225/169691127-324f5b34-b4f0-4b9b-a72a-6b108f173cc5.png)

Therefore, I would believe the issue is with SonoBus but I'm not sure. I don't know how to diagnose the issue. I don't get any errors when running the app from the command line or otherwise. Does SonoBus write any log files?

I don't think the problem is on the receiving SonoBus, computer B, either. If I try and connect computer B to a third computer C, they work just fine so the problem must be sending from A.

In fact, I tried using my bluetooth headset (I know it's not recommended but I'm just testing) as an input on both A and C. The same bluetooth headset works on computer C when connected to B but doesn't on computer A when connected to B. They are all running Windows 11. 

The problematic computer A is a Lenovo T480. SonoBus is allowed access to the microphone.

**Comment by essej** [comment]
Can you show a screenshot of the main screen with the input mixer expanded on computer A? (And connected to the group with computer B). Can you also show a shot of computer B connected to A as well?

**Comment by user1969903** [comment]
Well color me bamboozled. Never thought of checking there but now that you mentioned it, I did:

| A | B |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/33215225/169703215-b3f2010d-5142-4a3b-8fb3-d79b27accd6d.png)  | ![image](https://user-images.githubusercontent.com/33215225/169703298-f464f0cd-3917-4975-b727-8cc57d253971.png)   | 

As can be seen in the image, I have no input groups on computer A. I've added one and I now get audio streamed both ways. Not sure why I had to had it on A. Maybe something I've done.

In any case, Thanks for the hint!
