### ISSUE TITLE
Host a private server?

### ISSUE THREAD

**Issue by davidhaley** [sonosaurus/sonobus#129]
Sonobus is cool, thank you!

Is it possible to privately host the server that connects peers? The host is currently hard-coded throughout as `aoo.sonobus.net`

e.g.
https://github.com/sonosaurus/sonobus/blob/47ed1cfaaee634f26d206a0727cb089319b4ae8d/Source/ConnectView.cpp#L794
https://github.com/sonosaurus/sonobus/blob/47ed1cfaaee634f26d206a0727cb089319b4ae8d/Source/ConnectView.cpp#L841
https://github.com/sonosaurus/sonobus/blob/47ed1cfaaee634f26d206a0727cb089319b4ae8d/Source/ConnectView.cpp#L1003
https://github.com/sonosaurus/sonobus/blob/47ed1cfaaee634f26d206a0727cb089319b4ae8d/Source/ConnectView.cpp#L1034
https://github.com/sonosaurus/sonobus/blob/47ed1cfaaee634f26d206a0727cb089319b4ae8d/Source/ConnectView.cpp#L1540

Thank you.

**Comment by essej** [comment]
Yes, that's exactly what the connection server entry field in the Connect window lets you specify. If you want to build your own console server you'll find that at https://github.com/essej/aooserver . Or, every standalone instance exposes a connection server at port 10999 while it is running, so you can port forward through to that if you want to (and then you would have people specify your external IP:10999 (for example 11.22.33.44:10999) in the connection server field.

**Comment by davidhaley** [comment]
Cool. Thank you!
