### ISSUE TITLE
Using the standalone Sonobus app as a connection server fails

### ISSUE THREAD

**Issue by aleksati** [sonosaurus/sonobus#155]
Hi, 

I am trying to use the standalone Sonobus app itself as a connection server between two machines (as specified in the documentation and online that should be possible). However, I am unable to make it work... 

My procedure is:
 
On the "client" machine:
1. I open Sonobus app with default settings.
2. I click on "Connect"
3. In the "Private Group" I set a group name
4. In the "Connection Server" input field I write `IP-address-of-my-other-machine:10998`. 
5. Click on "Connect to group"

On the "server" machine: 
1. I open the Sonobus app with default settings. 
2. Nothing else is required, right? 

In every case, I get the same error message: `Failed because the connected party did not respond properly after a period of time, ...`

I have confirmed with Wireshark that my requests are being sent to the correct IP and port numbers. I also have disabled all firewalls (running Windows 10 on both machines). 

I am lucky to have access to a private ethernet connection VLAN where I am confident that all necessary ports (TCP/UDP 10998 and many UDP ports) are open. I have also tested it on 2 different WiFis and with port forwarding in order. I have tested this on all 3 networks and the error is the same.

There is not much documentation online about how to use the app itself as a connection server. Is there anything I am missing? Any tips?

**Comment by aleksati** [comment]
@essej ah, so the aoo.sonobus.net connection server is 10998, but the app connection server is on 10999?

**Comment by essej** [comment]
Correct, but I might change it in the future, because that is confusing!
