### ISSUE TITLE
show IP address of connected parties

### ISSUE THREAD

**Issue by strk** [sonosaurus/sonobus#157]
I've the impression the IP address of the connected users used to be shown, but I don't find it anymore. Was it moved anywhere else ? Or how to re-enable showing that info ? It's helpful to analyze routes and gather stats about best times to jam or do direct connection next time or use the connected partie's IP as aao server...

**Comment by essej** [comment]
It’s still in the same place, just takes an extra click… press on the Recv jitter buffer area, and at the top of the little popup it says click for IP address, click and it will appear. This was added so that people making screen captures don’t have to worry about privacy issues.

**Comment by strk** [comment]
Thanks! Resolved :)
