### ISSUE TITLE
PRIVACY ISSUE: unchecking "disable send" sends audio even when muted

### ISSUE THREAD

**Issue by strk** [sonosaurus/sonobus#158]
Concerning bug: checking the "Disable send" checkbox for a connected user and then unchecking it results in your audio being sent to that user EVEN IF your microphone is muted.

It's a really bad surprise because you see your microphone muted while instead someone (multiple people?) can still ear what you say !

This is happening with SonoBus 1.6.1

**Comment by essej** [comment]
OK, that's a valid concern, and a corner case not handled...

**Comment by strk** [comment]
I was looking for a way to _quickly_ toggle sending or not sending audio to a party, a button would be great (of course the muted microphone should disable sending to ALL, always).

Do you think I should file a separate ticket for the feature request of a button to enable/disable sending ?

**Comment by strk** [comment]
I don't know how but it looks like this is fixed now
