### ISSUE TITLE
[FEATURE] Default preferred receiving quality to NONE

### ISSUE THREAD

**Issue by strk** [sonosaurus/sonobus#164]
I'm experimenting with "bot users" (software agents) connecting to room to send information, but they throw away any received audio. In order to avoid the network traffic generated by new users joining the room sending audio to them, it would be nice for these "bot users" to express their preference being not receiving audio at all.

At the moment every new user will need to explicitly disable sending to the bot user, which is also not very easy to do ( see #159 )

**Comment by AtmanActive** [comment]
This would be useful for sending as well.

Many times the use case is for one-to-many monitoring. In those cases it is always a hassle to explain to each participant to disable their own send streams.

**Comment by essej** [comment]
If you join a group with both mute sending, and mute all others engaged (the bottom left two buttons), that’s exactly what happens. Not sure how you are creating these bots, though…

**Comment by strk** [comment]
Oh, I never used that second button, didn't know what it did. It's exactly what I'm after.
The bot is just me manually starting and configuring sonobus on a different PC. If you want to come and say hello I'm in "Sandro Studio" :)

**Comment by essej** [comment]
You can manually unmute people after you have pressed that button if you want to hear select individuals..

**Comment by strk** [comment]
I'd rather not even allow people to send that bot audio, but unfortunately toggling the mute button on and off re-enables sending audio to the bot even if the bot has that second (mute all others) button engaged, which might be the same bug reported in #158
