### ISSUE TITLE
Save Setup and File Picker popups not showing on Ubuntu 22.04

### ISSUE THREAD

**Issue by strk** [sonosaurus/sonobus#174]
I click it and nothing happens. @essej told me it's supposed to show a popup

**Comment by strk** [comment]
See #173

**Comment by strk** [comment]
Today I realized also the file picker popup doesn't show up.
For context, this is happening on an Ubuntu 22.04.2 LTS system using the Lubuntu (LXQT?) desktop environment

**Comment by strk** [comment]
I'm now trying with i3 under Ubuntu 22.04 LTS (where the initial issue was reported, while using LXQT) and the problem is also there. The working Mate DE setup was on a Debian 11

**Comment by essej** [comment]
If you have a chance and want to try to figure out what's going on here, please do feel free to dig in!

**Comment by strk** [comment]
I'm trying, and reporting here as I go. I hope you don't mind, it could be useful for whoever wants to help me.
Can you help me by pointing me at the file/line or expression that is supposed to open the file picker ?

**Comment by essej** [comment]
> I'm trying, and reporting here as I go. I hope you don't mind, it could be useful for whoever wants to help me.
> Can you help me by pointing me at the file/line or expression that is supposed to open the file picker ?

Aha! I think I might know what is going on: 

https://github.com/sonosaurus/sonobus/blob/404bbb407c28e0e4f551e4d53e40be5c7301126d/Source/SonobusPluginEditor.cpp#L2440

I bet there is not platform specific dialog available in certain desktop environments, and my fallback is.... nothing!

**Comment by essej** [comment]
So just get rid of the ` if (FileChooser::isPlatformDialogAvailable())`, around the whole thing... and the problem should be solved... it will use the non-native if it has to.

**Comment by essej** [comment]
If you want to test that, than PR it, I will merge it right in!

**Comment by essej** [comment]
There is one in OptionsView and ChatView as well.

**Comment by strk** [comment]
I confirm the non-native works. Will send a PR but do you have any idea about how to configure my desktop to advertise the existanc eof a native file chooser dialog ? Because I'd prefer using a native browser

**Comment by essej** [comment]
> I confirm the non-native works. Will send a PR but do you have any idea about how to configure my desktop to advertise the existanc eof a native file chooser dialog ? Because I'd prefer using a native browser

Great. Check this out, they are apparently checking for the existence of two different executables, kdialog or xenity:

https://github.com/sonosaurus/sonobus/blob/404bbb407c28e0e4f551e4d53e40be5c7301126d/deps/juce/modules/juce_gui_basics/native/juce_linux_FileChooser.cpp#L259

**Comment by strk** [comment]
> If you want to test that, than PR it, I will merge it right in!

Fix confirmed. See PR #179

**Comment by essej** [comment]
I have a variety of patches to JUCE and maintain my own fork, as they don’t generally accept or implement PRs from others. I use it on a variety of projects and I can handle it.

**Comment by strk** [comment]
Thanks, I've installed zenity and I'm happier. The PR is still good to have though (for those who don't have zenity)

**Comment by essej** [comment]
> Thanks, I've installed zenity and I'm happier. The PR is still good to have though (for those who don't have zenity)

Your PR, yes because that is a flat out bug!

**Comment by essej** [comment]
Haha. Honestly, I could merge it immediately but it wouldn’t help most people until I actually made a new release, which always takes a little  while… it will happen before that

**Comment by strk** [comment]
I'm one of those few people who are building from the develop branch,
and in order to contribute would need to continue doing so. Merging
early helps contributors by reducing the risk of change conflicts when
it is time to merge, and give a view of current "state of art", and a
bleeding edge version of the software. That's what the "develop"
branch is meant to be, isn't it ?

**Comment by essej** [comment]
DONE!

**Comment by strk** [comment]
Thanks, appreciated!
