### ISSUE TITLE
Android - use mic at all times, including locked screen

### ISSUE THREAD

**Issue by digitalsignalperson** [sonosaurus/sonobus#177]
Is there any way to allow mic use at all times?

I'm using Android 13 and the mic permission I can pick is "Allow only while using the app". There isn't a more open permission. When I turn off my screen or it locks, it will stop using the mic.

Maybe there is a way to build with an exemption for mic access
https://developer.android.com/guide/components/foreground-services#restrictions-exemptions

**Comment by digitalsignalperson** [comment]
Nvm, I think it is working now that I'm actually connected to another client.

**Comment by essej** [comment]
Yes, I only have it continue running in the background when an active connection with at least 1 person is there... but I think I am being a little too restrictive...
