### ISSUE TITLE
Auto-Reconnect to last group does not work with VST3 plugin

### ISSUE THREAD

**Issue by strk** [sonosaurus/sonobus#178]
Despite "Auto-Reconnect to last group" being checked in options, there's no auto-reconnect happening when SonoBus is loaded as a VST3 plugin.

**Comment by essej** [comment]
Thanks, just fixed this in latest develop...

**Comment by strk** [comment]
My setup is with Carla VST3 plugin host

**Comment by essej** [comment]
> I can't confirm this is working. It could be useful to include git-describe in the version string shown by Option to be able to report which commit-ish we're running

Are you saying you did or didn't try it after building and installing the VST3 from develop on your system?

**Comment by strk** [comment]
Current develop. After further digging I now realize this is due to not having anything in the "Recents" setup, so it's the "auto-save" (if it's supposed to be enabled, for VST) that is not working. I guess it's not supposed to be enabled ?

Everytime I start carla-single I get this message:
> [carla] Previous plugin state in '/home/strk/SonoBus.carxs' is non-existent, will start from default state

I'm starting it with:
> carla-single vst3 /usr/local/lib/vst3/SonoBus.vst3

**Comment by strk** [comment]
And I'm testing with commit ac3ae14fd4748f840e403c4f40959158940d2f07

**Comment by strk** [comment]
Closing as an invalid ticket
