### ISSUE TITLE
Group info is not being copied to clipboard (Linux)

### ISSUE THREAD

**Issue by strk** [sonosaurus/sonobus#184]
The "Copy Group Info" button is being ineffective for me. Nothing is copied to the clipboard.
The "Copy VDO.Ninja Video Link" works, so it's just the "Copy Group Info" that's failing. 

I've tested this after joining different channel, so does not have to do with auto-reconnect.
I've tested this with the standalone application, under i3 desktop environment in an Ubuntu 22-04 machine.

**Comment by essej** [comment]
Weird, works fine here on Mac so this may be good opportunity for you to track it down, since vdo.ninja link does work...

**Comment by strk** [comment]
Tested today, it works. Will reopen shall I ever see this again.
