### ISSUE TITLE
Where does Sonobus Save Its Setting

### ISSUE THREAD

**Issue by chigkim** [sonosaurus/sonobus#221]
I'm a screen reader user, and I accidentally selected a sound card that screen reader uses, and it locks up my screen reader when I run Sonobus. I can't do anything unless I quit Sonobus.
What can I delete in order to make Sonobus reinitialize its settings?
I'm both on Windows and Mac.
Thanks!

**Comment by chigkim** [comment]
Found it. %appdata%\sonobus

**Comment by essej** [comment]
And on Mac it’s ~/Library/Application Support/SonoBus/
