### ISSUE TITLE
No Sound For Usb Mic

### ISSUE THREAD

**Issue by chigkim** [sonosaurus/sonobus#222]
I'm having a problem getting Sonobus to get input signal from USB mics on windows.
I tested two USB mics: Zoom m2 and Samson q9u.
Both mics work fine in Reaper and Audacity on Mac and windows.
Both mics work fine with Sonobus on Mac, but It just doesn't work on Sonobus on Windows for some reason.
Metronome plays fine through the headphone out of the mic. It just won't get any input signal.
I put the input slider all the way up, but I hear nothing.
I installed Asio driver for Zoom m2, and tried all modes asio windows, windows low latency, etc.
I tried deleting the files inside %appdata%\Sonobus to reset.
Nothing seemed to work.
I'd really appreciate any help!

**Comment by essej** [comment]
Open open the input mixer in SonoBus (near top center of window), and make sure you see an input group there, and if not add one with the + button (with the appropriate channel count you want). Also make sure the inputs are checked in the audio options of the SonoBus settings.

**Comment by chigkim** [comment]
Thanks! For some reason, it just decided to work after a reboot!
