### ISSUE TITLE
Can't play audio asset when Dragging & Dropping asset into Soundboard

### ISSUE THREAD

**Issue by tcconway** [sonosaurus/sonobus#224]
Issue:
- Audio asset won't play in Soundboard when the asset is dragged in.
- Clicking the "+" and hitting the Browse button does work though.

Cause:
- When dragging an audio asset into soundboard, it creates the "cue", but only captures the filename without the full path. The app needs the full path to play the audio asset.

**Comment by essej** [comment]
Yeah, I fixed that here, for the next update.

**Comment by tcconway** [comment]
Many thanks! Excellent!
