### ISSUE TITLE
Distributing sonobus as Flatpak app 

### ISSUE THREAD

**Issue by disdi** [sonosaurus/sonobus#44]
This is to request sonobus to be distributed as Flatpak app on Linux. This would require sonobus to be published as a desktop app on [Flathub.](https://flathub.org/)

Flathub is a centralized repository of Flatpak apps. Once an app is included in Flathub, it can be easily installed by users, either using a graphical software center or the flatpak command line. It is also possible to provide a link that will open the app in a software center.

[Flatpak App Submission Process](https://github.com/flathub/flathub/wiki/App-Submission)

**Comment by kevinsmia1939** [comment]
Some progress here: https://github.com/sonosaurus/sonobus/issues/79

**Comment by Yajo** [comment]
This can be closed: https://flathub.org/apps/details/net.sonobus.SonoBus

Note: I think the flatpak option should appear in https://sonobus.net/linux.html
