### ISSUE TITLE
AppImage/Flatpak

### ISSUE THREAD

**Issue by reesericci** [sonosaurus/sonobus#51]
Please stop making snap the only binary, I don't want to compile!!! I religiously avoid snaps as the store is proprietary.

**Comment by essej** [comment]
I will also probably start making debs and rpm’s also, which I assume you would actually prefer more than flatpack, right? I may add a flatpack too, if it can be automated like snap is.

**Comment by reesericci** [comment]
I use arch, and there's an AUR package but not a binary. AppImages/Flatpaks work on an distro which is coolio.

**Comment by disdi** [comment]
> I will also probably start making debs and rpm’s also, which I assume you would actually prefer more than flatpack, right? I may add a flatpack too, if it can be automated like snap is.

I remember someone pointing out issues in creating debian packages for Debian due to Juce Library. Is it resolved now ?

btw, we already have an issue for flatpak image - https://github.com/essej/sonobus/issues/44

**Comment by kevinsmia1939** [comment]
Some Flatpak progress here: https://github.com/sonosaurus/sonobus/issues/79

**Comment by Yajo** [comment]
This can be closed: https://flathub.org/apps/details/net.sonobus.SonoBus

**Comment by essej** [comment]
Thanks!
