### ISSUE TITLE
Can't run on Linux Mint 20 Xfce (kinda solved)

### ISSUE THREAD

**Issue by jazznfunk** [sonosaurus/sonobus#60]
Such a nice project! Thank You at first! :)

Installed from flatpack. But i can't run sonobus from terminal:

compaq@compaq-Presario-CQ57-Notebook-PC:_~$ sonobus
Testing for explicit PulseAudio choice...
Testing for ALSA permissions...
...defaulting to using PulseAudio.
Illegal instruction (core dumped)
compaq@compaq-Presario-CQ57-Notebook-PC:_~$

This is similar on all 3 my linux machines, except one, who runs sonobus from terminal just fine.

**Comment by essej** [comment]
OK, I assume you meant the Snap install?  Did you 'sudo apt install jackd1' first, and also run 'sudo snap connect sonobus:jack1' ?

**Comment by jazznfunk** [comment]
Thank You for Your response!

Yes, Snap install (sudo snap install sonobus). Sorry for wrong terminology.
I planned to use Sonobus without jack, that's why i skip this step.

But anyway after uninstalling Sonobus (sudo snap remove sonobus), installing jackd1(sudo apt install jackd1), installing back sonobus from snap, running "sudo snap connect sonobus:jack1" i get the same "error" message.

If i connect sonobus to ALSA with "sudo snap connect sonobus:alsa", i get:

"Testing for explicit PulseAudio choice...
Testing for ALSA permissions...
...and using ALSA.
Illegal instruction (core dumped)"

I also installed aaoserver, but i doubt, it is somewhat connected to this.

**Comment by jazznfunk** [comment]
Thank You for Your response!

Yes, Snap install (sudo snap install sonobus). Sorry for wrong terminology.
I planned to use Sonobus without jack, that's why i skip this step.

But anyway after uninstalling Sonobus (sudo snap remove sonobus), installing jackd1(sudo apt install jackd1), installing back sonobus from snap, running "sudo snap connect sonobus:jack1" i get the same "error" message.

If i connect sonobus to ALSA with "sudo snap connect sonobus:alsa", i get:

"Testing for explicit PulseAudio choice...
Testing for ALSA permissions...
...and using ALSA.
Illegal instruction (core dumped)"

I also installed aaoserver, but i doubt, it is somewhat connected to this.

**Comment by jazznfunk** [comment]
I can confirm, that version 1.4.2 works with installation thru snap and installing jack1 as mentioned in user manual.
