### ISSUE TITLE
Question: Use desktop audio as input

### ISSUE THREAD

**Issue by Aggnog** [sonosaurus/sonobus#72]
Hi, 
I'm probably not using this software as it is intended, but I want to input my desktop audio from a pc into sonobus (like OBS would), then output it on a laptop, however I can't find a way to do this. There is no default option to input the desktop audio device since it appears as playback in the sound options, and not as a recording device (Digital Audio S/PDIF) High def audio device). I tried using VAC and I get an error on trying to add the cable output recorder as an input, ASIO also didn't work with any input options. Playback from file works as normal however.

Sorry for asking here, but I found no other page open to the community. 

Best regards

**Comment by essej** [comment]
Yeah, SonoBus is not a virtual cable solution on its own, you'll need to use other ones in order to make that happen. What exact errors were you getting when you tried VAC (or other similar things) as an input in sonobus? Probably screenshots of your setup and errors would be helpful...

**Comment by Aggnog** [comment]
I use external VAC already, input is set to default device and is showing audio levels https://i.imgur.com/VaH2wnI.png, here is the output https://i.imgur.com/pG5QtWu.png. Here it is set as input on the PC https://i.imgur.com/k94MMrP.png, i got all 8 audio points selected.  

If I try using the VAC as input using windows audio device type in sonobus I get this error https://i.imgur.com/x5KymAi.png, very generic and don't know if there are any more logs anywhere. 

On the laptop side I just have a usb audio device selected and it seems to work fine and testing works too https://i.imgur.com/vopZ3BZ.png

Playing a file from the PC also outputs correctly to the laptop, but desktop audio with or without the vac does not. 

Until now I've been using parsec gaming and it detects the High def audio device as input automatically but I don't need the video feed so it's kind of a waste. 

Hopefully this helps

**Comment by Aggnog** [comment]
Hi, 
I found a solution with Voicemeeter so this I'm closing the question. I do think it would be useful to allow this functionality more easily though in the future. 

Best regards

**Comment by mark-c** [comment]
So does this mean I can't use Sonobus to play my PC audio on an iphone?
