### ISSUE TITLE
if only checked "Each Connected User", then Record button *appears* to not function

### ISSUE THREAD

**Issue by ericfont** [sonosaurus/sonobus#76]
On 1.4.2, if I only check "Each Connected User" in the "Record features creates the following files:" option:

![image](https://user-images.githubusercontent.com/6502474/112529565-cb864400-8d7b-11eb-930e-2f1328d97d47.png)

Then pressing the record button results in the recording timestamp stuck at 0:00. And pressing the record button again to stop recording results in an empty waveform track with text "No audio file selected" being displayed at the bottom of sonobus:

![image](https://user-images.githubusercontent.com/6502474/112529930-39327000-8d7c-11eb-9b75-4624110f58b9.png)

Turns out that the audio from each connected user *does* record...a file for them is produced in my file system with their audio.  However sonobus *appears* to have failed recording.

**Comment by ericfont** [comment]
the file name listed as text in that track display refers to an incorrectly-named file.  That is probably the source of sonobus's confusion...maybe it is looking for files with one of the other track namings to be produced but forgot to about the case for "Each connected User".

Note this bug happens on both Arch and Debian linux machines I have.

**Comment by ericfont** [comment]
I should note that with current sonobus display I guess there is only one file track that can be displayed at a time (maybe there will be a future feature to have multiple tracks).  But maybe should default to showing at least the first connected user track in this case.

**Comment by essej** [comment]
Right, if a mix record isn't selected it doesn't know what file to look at for duration... it's silly.

**Comment by ericfont** [comment]
well in that case I'm going to submit a quick simple fix to prevent "Each Connected User" from being the only box checked.

**Comment by ericfont** [comment]
see #78 for a simple but crude fix.

**Comment by ericfont** [comment]
though could have easily just fixed it by looking for the corresponding connected user file.

**Comment by essej** [comment]
Yes, I think we'll just fix it right by doing that....

**Comment by ericfont** [comment]
ok, then I closed that PR.

(just thinking ahead, I do anticipate some minor issues if the first connected user drops out after recording has started but others remain...then that first user's recording file would halt and so their file wouldn't be a reliable indicator about whether recordings of the other remaining connected users are still continuing.)

**Comment by ericfont** [comment]
So the record button works now, thanks!  (I've even 

However, after completing the recording, sonobus appears to have failed recording as it presents an empty file:

![image](https://user-images.githubusercontent.com/6502474/113794247-173fd280-9718-11eb-9cb2-d8220e8d46f6.png)

Though I don't know the best way to present the recording to the user, because it is of course potentially any number of files based on the number of connected users...  And I have no idea if multiple open files is on the roadmap.  But a simple fallback would be to just default to show the first file in that folder.

**Comment by ericfont** [comment]
Though I will close this issue for now.  At least the "Reveal file" button works to reveal the folder.

**Comment by ericfont** [comment]
There is also an issue (though I don't want to bother you with too much) but if the sole peer I have connected drops out, and then reconnects in a bit, then the resulting file only contains audio from the time that recording started up until that peer dropped out, but doesn't contain the audio from when that peer returned.

I am just imagining situations where the person recording mistakenly assumes that the peer's audio upon rejoining will be recorded.  So at this point, that would unfortunatly be a mistaken assumption on their part.

But I will consider the original primary issue of "Record Button appearing not to work" to be closed, thank you.
