### ISSUE TITLE
I create Flatpak, but encounter error.

### ISSUE THREAD

**Issue by kevinsmia1939** [sonosaurus/sonobus#79]
I create Flatpak manifest file here.
https://github.com/kevinsmia1939/net.sonobus.SonoBus

Build it with
`flatpak-builder --install --user build net.sonobus.SonoBus.yaml --force-clean`

Run with
`flatpak run net.sonobus.SonoBus`

But I encounter error.
SonoBus start,  but only blank window.
```
[W][000020179.572669][module-rtkit.c:185 translate_error()] RTKit error: org.freedesktop.DBus.Error.Failed
[W][000020179.572723][module-rtkit.c:519 set_nice()] could not set nice-level to -11: Input/output error
[W][000020179.573961][module-rtkit.c:185 translate_error()] RTKit error: org.freedesktop.DBus.Error.Failed
[W][000020179.573983][module-rtkit.c:506 idle_func()] could not make thread realtime: Input/output error
```
Maybe issue with sandbox or missing dependencies?
https://github.com/sonosaurus/sonobus/issues/51
https://github.com/sonosaurus/sonobus/issues/44

**Comment by Yajo** [comment]
I think you should start opening the PR for flathub, following the app submission process. In my experience, Flathub maintainers are very helpful with packagers regarding those things.

Also, sonobus maintainers should track that PR, just in case they see something is not working fine on sonobus itself.

**Comment by kevinsmia1939** [comment]
@Yajo 
I would like to, but I think I want to atleast get it in working state before letting them see it.

**Comment by hfiguiere** [comment]
I do have a window shown. The RtKit shouldn't be fatal.

**Comment by essej** [comment]
@kevinsmia1939 @Yajo If you have a working flatpak build configuration, I will be happy to take over maintenance of it and retain control of the entry on flat hub. Please let me know.

**Comment by essej** [comment]
@kevinsmia1939  Also, I've switched the build to cmake in the develop branch and will be merging it very soon to main, which will completely break your existing flatpak yaml. If you could instead test it on the develop branch then I will merge your yaml into the sonobus repo itself.

**Comment by kevinsmia1939** [comment]
@essej 
I have working flatpak package now. You can try to install it.
https://github.com/flathub/flathub/pull/2250
You can take oven it if you want.

Right now the issue is default language selection. I guess because Flatpak prevent sonobus from reading system lang conf?

About the new build system cmake, it should be easy to update in Flatpak.

**Comment by essej** [comment]
If you have time to test flatpak building with the new cmake setup in the develop branch, that would be great. If not, let me know.

Does the default language selection work right for you when building and running directly on your system (no flatpak)?

**Comment by Yajo** [comment]
> I will be happy to take over maintenance of it and retain control of the entry on flat hub

That'd be the best thing to be done. I think you should express this desire directly in the flathub PR, so when the repo is created, it's made with the proper permissions.

**Comment by Yajo** [comment]
> Does the default language selection work right for you when building and running directly on your system (no flatpak)?

I just tested this. Same problem without Flatpak, so it seems it's a general separate issue. I'll open it now.

**Comment by Yajo** [comment]
I guess this can be closed 🎉 
https://flathub.org/apps/details/net.sonobus.SonoBus
