### ISSUE TITLE
Multi-Bus in Ableton Live 10 / 11

### ISSUE THREAD

**Issue by similicious** [sonosaurus/sonobus#80]
Thank you so much for this great piece of software. Me and my band are having a blast jamming together remotely during the pandemic.

I just updated Sonobus to the latest version and noticed that you added multi channel support, wich is great. I got it working in Reaper. In Ableton Live however, I couldn't get the Sonobus VST to recognize multi channel input.

I set up a track, routing the audio to Sonobus at channel 3/4:
![Ableton](https://user-images.githubusercontent.com/33279934/112752791-0636e900-8fd5-11eb-8383-cb01b9bdb564.PNG)

But Sonobus doesn't show these inputs in the mixer:
![Sonobus](https://user-images.githubusercontent.com/33279934/112752812-1c44a980-8fd5-11eb-9664-5b92da93dafa.PNG)

Is this a limitation of Live? The [official docs ](https://help.ableton.com/hc/en-us/articles/209773065-Using-multi-out-plug-ins) say, that Live supports multiple ins and outs. Also I already used multi-out plugins (EZ Drummer) in Live. EZ-Drummer doesn't seem to dynamically detect the number of outputs. Instead these outputs are static and you can choose wether or not you want to use them. Sonobus doesn't recognize multiple monitor outputs either.

Best regards
Simon

**Comment by Spacechild1** [comment]
> The official docs say, that Live supports multiple ins and outs

They probably refer to multiple *channels* (= more than 2). VST3 added the possibility to have several input/output busses where each bus can have multiple channels. In that sense, VST2 plugins only ever have a single input/output bus. It seems like Live doesn't support multi-bus plugins (yet).

**Comment by similicious** [comment]
I got it working! Thank you for mentioning VST3. I was using the VST2-Version in Live.

Using the VST3 plugin, everything works as expected.

**Comment by essej** [comment]
Yes, I was going to say you have to use the VST3 because I limited the VST2 intentionally so it would work in OBS which crashes when more buses are exposed. It is strange that when using it the VST2 in Ableton even shows all those possible routing channels... I wouldn't expect it to.
