### ISSUE TITLE
Linux Version show 1.4.2 Synaptic Says 1.4.3

### ISSUE THREAD

**Issue by kendoori** [sonosaurus/sonobus#85]
Linux Mint 20.1

```
sonobus --version
SonoBus version 1.4.2

```

![image](https://user-images.githubusercontent.com/2447420/113937009-8e33a480-97c6-11eb-8846-6f5d4e63258f.png)

I installed from source, also via the .deb.

![image](https://user-images.githubusercontent.com/2447420/113937134-b58a7180-97c6-11eb-8dbb-440d1eb2110a.png)

**Comment by essej** [comment]
Wait, you installed it 3 different ways?

**Comment by kendoori** [comment]
This was an earlier reason to install from source. How can I completely uninstall and start again?

**Comment by essej** [comment]
OK, to uninstall a previous source build, go the checked out source code (cd sonobus/Builds/LinuxMakefile) in a terminal, then run 'sudo ./uninstall'.

To uninstall the snap build (if you installed it), run 'sudo snap remove sonobus'

To uninstall the deb, run 'sudo apt remove sonobus'.

Now, I recommend that you just install the debian package from our repo by following the instructions in the first section here: https://sonobus.net/linux.html . Please note that our repo location may have changed from before, so do all the steps again.

**Comment by kendoori** [comment]
OK, I'm good.
