### ISSUE TITLE
Doesn't support architecture 'i386' Mint 20.1

### ISSUE THREAD

**Issue by kendoori** [sonosaurus/sonobus#91]
Minor nit. I was offered to upgrade to latest today. When I did apt update, this was presented. Since I'm on 64-bit, I was able to complete the upgrade. Something seems off at the PPA-level.

`N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'http://pkg.sonobus.net/apt stable InRelease' doesn't support architecture 'i386'`

**Comment by matthewevans** [comment]
@kendoori apt will complain if certain architectures aren't present in the repo. It's just a warning and normally could be suppressed with adding `[arch=amd64]` after `deb` in the /etc/apt/sources.list.d/sonobus.list file.

You won't need to do that as a 32-bit version was built and added to the repo this morning. Thanks for the heads up!
